name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, miri
      - name: Lint
        run: cargo fmt --check
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: Check (feature power-set)
        run: cargo hack check --feature-powerset
      - name: Test
        run: cargo test --all-features
      - name: Test (all-features)
        run: cargo test --all-features
      - name: Setup Miri
        run: cargo miri setup
      - name: Test (miri all-features)
        run: cargo miri test --all-features
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install cargo-fuzz
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-fuzz
          locked: false
      - name: Fuzz
        run: RUST_BACKTRACE=1 cargo fuzz run fuzz -- -max_total_time=900 -timeout=5